# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('testall', 
    ['traci-applications', 'wave', 'netanim', 'traci',
    'millicar','core', 'propagation', 'spectrum', 'mmwave'])
    obj.source = 'testall.cc'

